# Generated by Django 5.0.6 on 2024-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_tittle', models.CharField(max_length=50)),
                ('task_des', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
