# Generated by Django 5.0.6 on 2024-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('task_model', models.ManyToManyField(to='add_task_app.taskmodel')),
            ],
        ),
    ]
